### PR TITLE
Add SMR measures

### PR DESCRIPTION
**Pull request by chrisjwood16**
Add SMR measures for ethnicity 16 grouping.
Add SMR measures grouped by age / sex for standardisation
Adjust catagorize as age banding to final used

### CODE REVIEW

**Review by speed-vm — COMMENTED** [review]
@chrisjwood16  Please can you check the monthly SMR stratified by the high risk drugs the 'Groupby is using 'last_12m'

**Review by speed-vm — COMMENTED** [review]
Yes this commit looks good to me

**Review by speed-vm — COMMENTED** [review]
@chrisjwood16 In the project yaml, is this an old measure? generate_measures_mr_smr

**Comment by chrisjwood16** [comment]
> @chrisjwood16 Please can you check the monthly SMR stratified by the high risk drugs the 'Groupby is using 'last_12m'

The 12m here refers to prescriptions - we specified for example on a DMARD meant >=2 prescriptions for a DMARD in the last 12m.

**Comment by chrisjwood16** [comment]
> @chrisjwood16 In the project yaml, is this an old measure? generate_measures_mr_smr

This is the action we use to generate measures from the original study definition (MR and SMR). We will be using it here to get the SMR measures.

**Comment by speed-vm** [comment]
@chrisjwood16 happy with the commits, will let you merge.

**Pull request merged**
